# Netlify configuration file

# Build settings
[build]
  command = "npm run build"
  publish = "dist"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to ensure SPA works correctly
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"